project_id = "ghfrddcmkexifhcwyupu"

[functions.replicate]
verify_jwt = true

[functions.replicate-enhanced]
verify_jwt = true

[functions.gemini-nano]
verify_jwt = true

[functions.openai-image]
verify_jwt = false

[functions.huggingface-image]
verify_jwt = false

[functions.openai-text]
verify_jwt = false

[functions.template-composer]
verify_jwt = true